version: '3'

services: 
  app: 
    container_name: 'cd-bag_app'
    build: .
    entrypoint: 'dockerize -wait tcp://db:5432 -timeout 45s .docker/entrypoint.sh'
    ports: 
      - 3333:3333
    volumes: 
      - .:/home/node/app
    depends_on: 
      - db

  db: 
    container_name: 'cd-bag_db'
    build: ./.docker/postgres/
    ports: 
      - 5432:5432
