version: '3.9'

services: 
  app: 
    build: .
    container_name: 'cd-bag_app'
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229 
    volumes: 
      - .:/usr/app
    links: 
      - cd-bag_db
    depends_on: 
      - db

  db: 
    image: postgres
    container_name: 'cd-bag_db'
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cd-bag_db
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local